version: '3.8'

services:
  # Configuración para la primera web (Puerto 4000)
  web01:
    image: nginx:alpine
    container_name: servidor-bruno-4000
    ports:
      - "4000:80"
    volumes:
      - ./src/web01:/usr/share/nginx/html

  # Configuración para la segunda web (Puerto 4001)
  web02:
    image: nginx:alpine
    container_name: servidor-bruno-4001
    ports:
      - "4001:80"
    volumes:
      - ./src/web02:/usr/share/nginx/html